services:
  strava_komoot_sync:
    image: ghcr.io/aexel90/strava_komoot_sync:latest
    container_name: strava_komoot_sync
    restart: on-failure:2
    env_file:
      - .env
    volumes:
      - ./token.json:/token.json